// Generated by Selenium IDE
const { Builder, By } = require('selenium-webdriver')
const assert = require('assert')

describe('register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('register', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css("li:nth-child(3) > a")).click()
    await driver.findElement(By.css("li:nth-child(2) > a")).click()
    await driver.findElement(By.name("email")).sendKeys("ahmartariq@yahoo.com")
    await driver.findElement(By.name("password")).sendKeys("ahmar123")
    await driver.findElement(By.css(".row > a")).click()
    {
      const element = await driver.findElement(By.css(".row > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("email")).sendKeys("ahmartariq@yahoo.com")
    await driver.findElement(By.name("password")).sendKeys("ahmar123")
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("name")).sendKeys("ahmar")
  })

  it('login', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css("li:nth-child(3) > a")).click()
    await driver.findElement(By.css("li:nth-child(2) > a")).click()
    await driver.findElement(By.name("email")).sendKeys("ahmartariq1@yahoo.com")
    await driver.findElement(By.name("password")).sendKeys("ahmar123")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.css("button")).click()
  })

  it('add product', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css("li:nth-child(2) > a")).click()
    await driver.findElement(By.name("email")).sendKeys("admin1@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("admin123")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.css("li:nth-child(2) > a")).click()
    await driver.findElement(By.id("product_id")).sendKeys("2312314")
    await driver.findElement(By.id("title")).sendKeys("testing")
    await driver.findElement(By.id("price")).sendKeys("100000")
    await driver.findElement(By.id("description")).sendKeys("TESTINGGGGGG")
    await driver.findElement(By.id("content")).sendKeys("AODINASIODNAO ")
    await driver.findElement(By.name("category")).click()
    {
      const dropdown = await driver.findElement(By.name("category"))
      await dropdown.findElement(By.xpath("//option[. = 'Laptops']")).click()
    }
    await driver.findElement(By.css("button")).click()
  })

  it('delete product', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css("li:nth-child(2) > a")).click()
    await driver.findElement(By.name("email")).sendKeys("admin1@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("admin123")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("btn_buy")).click()
  })

  it('update product', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css("li:nth-child(2) > a")).click()
    await driver.findElement(By.name("email")).sendKeys("admin1@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("admin123")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("btn_view")).click()
    await driver.findElement(By.id("price")).click()
    await driver.findElement(By.id("price")).sendKeys("400.99")
    await driver.findElement(By.css("button")).click()
  })
})
